// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/kafka"
	"github.com/bborbe/kafka-topic-reader/pkg"
)

type ChangesProvider struct {
	ChangesStub        func(context.Context, kafka.Topic, kafka.Partition, kafka.Offset, uint64, []byte) (pkg.Records, error)
	changesMutex       sync.RWMutex
	changesArgsForCall []struct {
		arg1 context.Context
		arg2 kafka.Topic
		arg3 kafka.Partition
		arg4 kafka.Offset
		arg5 uint64
		arg6 []byte
	}
	changesReturns struct {
		result1 pkg.Records
		result2 error
	}
	changesReturnsOnCall map[int]struct {
		result1 pkg.Records
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ChangesProvider) Changes(arg1 context.Context, arg2 kafka.Topic, arg3 kafka.Partition, arg4 kafka.Offset, arg5 uint64, arg6 []byte) (pkg.Records, error) {
	var arg6Copy []byte
	if arg6 != nil {
		arg6Copy = make([]byte, len(arg6))
		copy(arg6Copy, arg6)
	}
	fake.changesMutex.Lock()
	ret, specificReturn := fake.changesReturnsOnCall[len(fake.changesArgsForCall)]
	fake.changesArgsForCall = append(fake.changesArgsForCall, struct {
		arg1 context.Context
		arg2 kafka.Topic
		arg3 kafka.Partition
		arg4 kafka.Offset
		arg5 uint64
		arg6 []byte
	}{arg1, arg2, arg3, arg4, arg5, arg6Copy})
	stub := fake.ChangesStub
	fakeReturns := fake.changesReturns
	fake.recordInvocation("Changes", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6Copy})
	fake.changesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *ChangesProvider) ChangesCallCount() int {
	fake.changesMutex.RLock()
	defer fake.changesMutex.RUnlock()
	return len(fake.changesArgsForCall)
}

func (fake *ChangesProvider) ChangesCalls(stub func(context.Context, kafka.Topic, kafka.Partition, kafka.Offset, uint64, []byte) (pkg.Records, error)) {
	fake.changesMutex.Lock()
	defer fake.changesMutex.Unlock()
	fake.ChangesStub = stub
}

func (fake *ChangesProvider) ChangesArgsForCall(i int) (context.Context, kafka.Topic, kafka.Partition, kafka.Offset, uint64, []byte) {
	fake.changesMutex.RLock()
	defer fake.changesMutex.RUnlock()
	argsForCall := fake.changesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *ChangesProvider) ChangesReturns(result1 pkg.Records, result2 error) {
	fake.changesMutex.Lock()
	defer fake.changesMutex.Unlock()
	fake.ChangesStub = nil
	fake.changesReturns = struct {
		result1 pkg.Records
		result2 error
	}{result1, result2}
}

func (fake *ChangesProvider) ChangesReturnsOnCall(i int, result1 pkg.Records, result2 error) {
	fake.changesMutex.Lock()
	defer fake.changesMutex.Unlock()
	fake.ChangesStub = nil
	if fake.changesReturnsOnCall == nil {
		fake.changesReturnsOnCall = make(map[int]struct {
			result1 pkg.Records
			result2 error
		})
	}
	fake.changesReturnsOnCall[i] = struct {
		result1 pkg.Records
		result2 error
	}{result1, result2}
}

func (fake *ChangesProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ChangesProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.ChangesProvider = new(ChangesProvider)
